import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { AvailabilityStatus, MenuPurpose, MenuStatus } from '@prisma/client';
import { AdminTokenPayload } from '../auth/auth.types.js';
import { AdminAccessService } from '../admin/admin-access.service.js';
import { PrismaService } from '../prisma/prisma.service.js';

type Translations = Record<'ka' | 'en' | 'ru', { name: string; description?: string; recipe?: string }>;

@Injectable()
export class CatalogService {
  constructor(private readonly prisma: PrismaService, private readonly access: AdminAccessService) {}
  private async audit(actor: AdminTokenPayload, action: string, entityType: string, entityId: string, metadata?: object) { await this.prisma.adminAuditEvent.create({ data: { restaurantId: actor.restaurantId, adminUserId: actor.sub, action, entityType, entityId, metadata } }); }
  private translations(value: Translations) { return (['ka', 'en', 'ru'] as const).map((languageCode) => ({ languageCode, name: value[languageCode]?.name?.trim(), description: value[languageCode]?.description?.trim() || undefined, recipe: value[languageCode]?.recipe?.trim() || undefined })); }
  private assertTranslations(value: Translations) { for (const code of ['ka', 'en', 'ru'] as const) if (!value?.[code]?.name?.trim()) throw new ConflictException(`Missing ${code} name`); }

  async menus(actor: AdminTokenPayload) { await this.access.assert(actor, 'menus.view'); return this.prisma.menu.findMany({ where: { restaurantId: actor.restaurantId, status: { not: 'DELETED' } }, include: { translations: true, _count: { select: { categories: true, dishes: true } } }, orderBy: [{ isSystem: 'desc' }, { createdAt: 'asc' }] }); }
  async createMenu(actor: AdminTokenPayload, data: { translations: Translations; status?: MenuStatus; isDefault?: boolean }) { await this.access.assert(actor, 'menus.manage'); this.assertTranslations(data.translations); if (data.isDefault) await this.prisma.menu.updateMany({ where: { restaurantId: actor.restaurantId }, data: { isDefault: false } }); const menu = await this.prisma.menu.create({ data: { restaurantId: actor.restaurantId, purpose: MenuPurpose.POS, status: data.status ?? 'ACTIVE', isDefault: data.isDefault ?? false, translations: { create: this.translations(data.translations) } }, include: { translations: true } }); await this.audit(actor, 'MENU_CREATED', 'Menu', menu.id); return menu; }
  async updateMenu(actor: AdminTokenPayload, menuId: string, data: { translations: Translations; status?: MenuStatus; isDefault?: boolean }) { await this.access.assert(actor, 'menus.manage'); this.assertTranslations(data.translations); const menu = await this.prisma.menu.findFirst({ where: { id: menuId, restaurantId: actor.restaurantId } }); if (!menu) throw new NotFoundException('Menu not found'); if (menu.isSystem && data.status && data.status !== 'ACTIVE') throw new ConflictException('The QR menu must remain active.'); if (data.isDefault) await this.prisma.menu.updateMany({ where: { restaurantId: actor.restaurantId, id: { not: menuId } }, data: { isDefault: false } }); await this.prisma.menuTranslation.deleteMany({ where: { menuId } }); const updated = await this.prisma.menu.update({ where: { id: menuId }, data: { status: menu.isSystem ? 'ACTIVE' : data.status, isDefault: menu.isSystem ? false : data.isDefault, translations: { create: this.translations(data.translations) } }, include: { translations: true } }); await this.audit(actor, 'MENU_UPDATED', 'Menu', menuId); return updated; }
  async deleteMenu(actor: AdminTokenPayload, menuId: string) { await this.access.assert(actor, 'menus.manage'); const menu = await this.prisma.menu.findFirst({ where: { id: menuId, restaurantId: actor.restaurantId } }); if (!menu) throw new NotFoundException('Menu not found'); if (menu.isSystem) throw new ConflictException('The QR menu cannot be deleted.'); await this.prisma.menu.update({ where: { id: menuId }, data: { status: 'DELETED', isDefault: false, deletedAt: new Date() } }); await this.audit(actor, 'MENU_SOFT_DELETED', 'Menu', menuId); return { id: menuId }; }
  async menuStructure(actor: AdminTokenPayload, menuId: string) { await this.access.assert(actor, 'menus.view'); const menu = await this.prisma.menu.findFirst({ where: { id: menuId, restaurantId: actor.restaurantId, status: { not: 'DELETED' } }, include: { translations: true, categories: { include: { category: { include: { translations: true } } }, orderBy: { sortOrder: 'asc' } }, dishes: { include: { dish: { include: { translations: true } } }, orderBy: { sortOrder: 'asc' } } } }); if (!menu) throw new NotFoundException('Menu not found'); return menu; }
  async saveMenuCategories(actor: AdminTokenPayload, menuId: string, items: { categoryId: string; sortOrder: number; status?: AvailabilityStatus }[]) { await this.access.assert(actor, 'menus.manage'); const categories = await this.prisma.category.findMany({ where: { id: { in: items.map((item) => item.categoryId) }, restaurantId: actor.restaurantId, deletedAt: null }, select: { id: true } }); if (categories.length !== items.length) throw new NotFoundException('One or more categories were not found'); await this.prisma.$transaction([this.prisma.menuCategory.deleteMany({ where: { menuId } }), this.prisma.menuCategory.createMany({ data: items.map((item) => ({ menuId, categoryId: item.categoryId, sortOrder: item.sortOrder, status: item.status ?? 'AVAILABLE' })) })]); await this.audit(actor, 'MENU_CATEGORIES_UPDATED', 'Menu', menuId); return this.menuStructure(actor, menuId); }
  async saveMenuDishes(actor: AdminTokenPayload, menuId: string, items: { dishId: string; sortOrder: number; status?: AvailabilityStatus; priceOverride?: number | null }[]) { await this.access.assert(actor, 'menus.manage'); const dishes = await this.prisma.dish.findMany({ where: { id: { in: items.map((item) => item.dishId) }, restaurantId: actor.restaurantId, deletedAt: null }, select: { id: true, categoryId: true } }); if (dishes.length !== items.length) throw new NotFoundException('One or more dishes were not found'); const menuCategories = await this.prisma.menuCategory.findMany({ where: { menuId }, select: { categoryId: true } }); const categoryIds = new Set(menuCategories.map((item) => item.categoryId)); if (dishes.some((dish) => !categoryIds.has(dish.categoryId))) throw new ConflictException('Each menu dish must belong to a selected menu category'); await this.prisma.$transaction([this.prisma.menuDish.deleteMany({ where: { menuId } }), this.prisma.menuDish.createMany({ data: items.map((item) => ({ menuId, dishId: item.dishId, sortOrder: item.sortOrder, status: item.status ?? 'AVAILABLE', priceOverride: item.priceOverride ?? null })) })]); await this.audit(actor, 'MENU_DISHES_UPDATED', 'Menu', menuId); return this.menuStructure(actor, menuId); }

  async categories(actor: AdminTokenPayload) { await this.access.assert(actor, 'categories.view'); return this.prisma.category.findMany({ where: { restaurantId: actor.restaurantId, deletedAt: null }, include: { translations: true }, orderBy: { sortOrder: 'asc' } }); }
  async createCategory(actor: AdminTokenPayload, data: { translations: Translations; imageUrl?: string; status?: AvailabilityStatus }) { await this.access.assert(actor, 'categories.manage'); this.assertTranslations(data.translations); const sortOrder = await this.prisma.category.count({ where: { restaurantId: actor.restaurantId } }); const category = await this.prisma.category.create({ data: { restaurantId: actor.restaurantId, imageUrl: data.imageUrl, status: data.status ?? 'AVAILABLE', sortOrder, translations: { create: this.translations(data.translations).map(({ languageCode, name }) => ({ languageCode, name })) } }, include: { translations: true } }); await this.addToQrMenu(actor.restaurantId, 'category', category.id, sortOrder); await this.audit(actor, 'CATEGORY_CREATED', 'Category', category.id); return category; }
  async updateCategory(actor: AdminTokenPayload, categoryId: string, data: { translations: Translations; imageUrl?: string; status?: AvailabilityStatus }) { await this.access.assert(actor, 'categories.manage'); this.assertTranslations(data.translations); const category = await this.prisma.category.findFirst({ where: { id: categoryId, restaurantId: actor.restaurantId, deletedAt: null } }); if (!category) throw new NotFoundException('Category not found'); await this.prisma.categoryTranslation.deleteMany({ where: { categoryId } }); const updated = await this.prisma.category.update({ where: { id: categoryId }, data: { imageUrl: data.imageUrl, status: data.status, translations: { create: this.translations(data.translations).map(({ languageCode, name }) => ({ languageCode, name })) } }, include: { translations: true } }); await this.audit(actor, 'CATEGORY_UPDATED', 'Category', categoryId); return updated; }
  async deleteCategory(actor: AdminTokenPayload, categoryId: string) {
    await this.access.assert(actor, 'categories.manage');
    const category = await this.prisma.category.findFirst({ where: { id: categoryId, restaurantId: actor.restaurantId, deletedAt: null }, select: { id: true } });
    if (!category) throw new NotFoundException('Category not found');
    const qrMenu = await this.prisma.menu.findFirst({ where: { restaurantId: actor.restaurantId, code: 'QR_MENU', isSystem: true } });
    await this.prisma.$transaction(async (tx) => {
      await tx.category.update({ where: { id: categoryId }, data: { status: 'HIDDEN', deletedAt: new Date() } });
      if (qrMenu) {
        await tx.menuDish.deleteMany({ where: { menuId: qrMenu.id, dish: { categoryId } } });
        await tx.menuCategory.deleteMany({ where: { menuId: qrMenu.id, categoryId } });
      }
    });
    await this.audit(actor, 'CATEGORY_SOFT_DELETED', 'Category', categoryId, { removedFromQrMenu: Boolean(qrMenu) });
    return { id: categoryId };
  }

  async dishes(actor: AdminTokenPayload, page = 1, pageSize = 20, search = '') { await this.access.assert(actor, 'dishes.view'); const where = { restaurantId: actor.restaurantId, deletedAt: null, ...(search ? { translations: { some: { name: { contains: search, mode: 'insensitive' as const } } } } : {}) }; const [items, total] = await this.prisma.$transaction([this.prisma.dish.findMany({ where, include: { translations: true, category: { include: { translations: true } } }, orderBy: { sortOrder: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.dish.count({ where })]); return { items, page, pageSize, total }; }
  async createDish(actor: AdminTokenPayload, data: { categoryId: string; translations: Translations; imageUrl?: string; priceAmount: number; calories?: number; status?: AvailabilityStatus }) { await this.access.assert(actor, 'dishes.manage'); this.assertTranslations(data.translations); const category = await this.prisma.category.findFirst({ where: { id: data.categoryId, restaurantId: actor.restaurantId, deletedAt: null } }); if (!category) throw new NotFoundException('Category not found'); const sortOrder = await this.prisma.dish.count({ where: { categoryId: category.id } }); const dish = await this.prisma.dish.create({ data: { restaurantId: actor.restaurantId, categoryId: category.id, imageUrl: data.imageUrl, priceAmount: data.priceAmount, calories: data.calories, status: data.status ?? 'AVAILABLE', sortOrder, translations: { create: this.translations(data.translations).map(({ languageCode, name, description, recipe }) => ({ languageCode, name, description: description ?? '', recipe })) } }, include: { translations: true } }); await this.addToQrMenu(actor.restaurantId, 'dish', dish.id, sortOrder); await this.audit(actor, 'DISH_CREATED', 'Dish', dish.id); return dish; }
  async updateDish(actor: AdminTokenPayload, dishId: string, data: { categoryId: string; translations: Translations; imageUrl?: string; priceAmount: number; calories?: number; status?: AvailabilityStatus }) { await this.access.assert(actor, 'dishes.manage'); this.assertTranslations(data.translations); const dish = await this.prisma.dish.findFirst({ where: { id: dishId, restaurantId: actor.restaurantId, deletedAt: null } }); if (!dish) throw new NotFoundException('Dish not found'); await this.prisma.dishTranslation.deleteMany({ where: { dishId } }); const updated = await this.prisma.dish.update({ where: { id: dishId }, data: { categoryId: data.categoryId, imageUrl: data.imageUrl, priceAmount: data.priceAmount, calories: data.calories, status: data.status, translations: { create: this.translations(data.translations).map(({ languageCode, name, description, recipe }) => ({ languageCode, name, description: description ?? '', recipe })) } }, include: { translations: true } }); await this.audit(actor, 'DISH_UPDATED', 'Dish', dishId); return updated; }
  async deleteDish(actor: AdminTokenPayload, dishId: string) { await this.access.assert(actor, 'dishes.manage'); const result = await this.prisma.dish.updateMany({ where: { id: dishId, restaurantId: actor.restaurantId, deletedAt: null }, data: { status: 'HIDDEN', deletedAt: new Date() } }); if (!result.count) throw new NotFoundException('Dish not found'); await this.audit(actor, 'DISH_SOFT_DELETED', 'Dish', dishId); return { id: dishId }; }

  private async addToQrMenu(restaurantId: string, kind: 'category' | 'dish', itemId: string, sortOrder: number): Promise<void> {
    const menu = await this.prisma.menu.findFirst({ where: { restaurantId, code: 'QR_MENU', purpose: MenuPurpose.QR, isSystem: true } });
    if (!menu) return;
    if (kind === 'category') await this.prisma.menuCategory.upsert({ where: { menuId_categoryId: { menuId: menu.id, categoryId: itemId } }, update: {}, create: { menuId: menu.id, categoryId: itemId, sortOrder } });
    else await this.prisma.menuDish.upsert({ where: { menuId_dishId: { menuId: menu.id, dishId: itemId } }, update: {}, create: { menuId: menu.id, dishId: itemId, sortOrder } });
  }
}
