import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import * as argon2 from 'argon2';
import { randomInt } from 'node:crypto';
import { AdminTokenPayload } from '../auth/auth.types.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { AdminAccessService } from './admin-access.service.js';
import { CreateStaffDto } from './dto/create-staff.dto.js';
import { SaveRoleDto } from './dto/save-role.dto.js';
import { UpdatePosSettingsDto } from './dto/update-pos-settings.dto.js';
import { UpdateStaffDto } from './dto/update-staff.dto.js';

@Injectable()
export class AdminService {
  constructor(private readonly prisma: PrismaService, private readonly access: AdminAccessService) {}
  private ensureRestaurant(actor: AdminTokenPayload, restaurantId: string): void { if (actor.restaurantId !== restaurantId) throw new ForbiddenException(); }
  private async audit(actor: AdminTokenPayload, action: string, entityType: string, entityId: string, metadata?: Prisma.InputJsonValue): Promise<void> { await this.prisma.adminAuditEvent.create({ data: { restaurantId: actor.restaurantId, adminUserId: actor.sub, action, entityType, entityId, metadata } }); }
  private async roleIds(restaurantId: string, roleIds: string[] = []): Promise<string[]> { const roles = await this.prisma.role.findMany({ where: { id: { in: roleIds }, restaurantId, isActive: true }, select: { id: true } }); if (roles.length !== roleIds.length) throw new NotFoundException('One or more roles were not found'); return roles.map((role) => role.id); }
  private async permissionIds(codes: string[] = []): Promise<{ id: string; code: string }[]> { const permissions = await this.prisma.permission.findMany({ where: { code: { in: codes } }, select: { id: true, code: true } }); if (permissions.length !== codes.length) throw new NotFoundException('One or more permissions were not found'); return permissions; }
  private staffResult(staff: { id: string; firstName: string; lastName: string; email: string | null; phone: string | null; isActive: boolean; roles: { role: { id: string; name: string } }[]; permissions: { permission: { code: string }; isGranted: boolean }[] }) { return { id: staff.id, firstName: staff.firstName, lastName: staff.lastName, email: staff.email, phone: staff.phone, isActive: staff.isActive, roles: staff.roles.map((item) => item.role), directPermissions: staff.permissions.map((item) => ({ code: item.permission.code, isGranted: item.isGranted })) }; }
  private deliveryTarget(staff: { email: string | null; phone: string | null }) { if (staff.email) return { type: 'email', destination: staff.email }; if (staff.phone) return { type: 'sms', destination: staff.phone }; throw new ConflictException('A staff member must have an email or phone number'); }

  async getSettings(actor: AdminTokenPayload, restaurantId: string) { await this.access.assert(actor, 'settings.view'); this.ensureRestaurant(actor, restaurantId); const settings = await this.prisma.restaurantPosSettings.findUnique({ where: { restaurantId } }); if (!settings) throw new NotFoundException('Restaurant settings not found'); return { restaurantId, businessDayStart: settings.businessDayStartsAt, businessDayEnd: settings.businessDayEndsAt, serviceFeePercent: Number(settings.serviceChargePercent ?? 0), defaultLanguage: 'ka' as const }; }
  async updateSettings(actor: AdminTokenPayload, restaurantId: string, patch: UpdatePosSettingsDto) { await this.access.assert(actor, 'settings.update'); this.ensureRestaurant(actor, restaurantId); const settings = await this.prisma.restaurantPosSettings.update({ where: { restaurantId }, data: { businessDayStartsAt: patch.businessDayStart, businessDayEndsAt: patch.businessDayEnd, serviceChargePercent: patch.serviceFeePercent } }); await this.audit(actor, 'POS_SETTINGS_UPDATED', 'RestaurantPosSettings', settings.id, patch as Prisma.InputJsonValue); return this.getSettings(actor, restaurantId); }

  async listStaff(actor: AdminTokenPayload) { await this.access.assert(actor, 'staff.view'); const staff = await this.prisma.staffMember.findMany({ where: { restaurantId: actor.restaurantId }, include: { roles: { include: { role: true } }, permissions: { include: { permission: true } } }, orderBy: [{ firstName: 'asc' }, { lastName: 'asc' }] }); return staff.map((item) => this.staffResult(item)); }
  async createStaff(actor: AdminTokenPayload, data: CreateStaffDto) { await this.access.assert(actor, 'staff.create'); if (!data.email && !data.phone) throw new ConflictException('Email or phone is required'); const roles = await this.roleIds(actor.restaurantId, data.roleIds); const permissions = await this.permissionIds(data.permissionCodes); const pin = String(randomInt(0, 10000)).padStart(4, '0'); const staff = await this.prisma.staffMember.create({ data: { restaurantId: actor.restaurantId, firstName: data.firstName.trim(), lastName: data.lastName.trim(), email: data.email?.toLowerCase(), phone: data.phone?.trim(), pinHash: await argon2.hash(pin, { type: argon2.argon2id }), roles: { create: roles.map((roleId) => ({ roleId })) }, permissions: { create: permissions.map((permission) => ({ permissionId: permission.id, isGranted: true })) }, }, include: { roles: { include: { role: true } }, permissions: { include: { permission: true } } } }); const delivery = this.deliveryTarget(staff); await this.audit(actor, 'STAFF_CREATED', 'StaffMember', staff.id); await this.audit(actor, 'PIN_DELIVERY_MOCKED', 'StaffMember', staff.id, delivery); return { staff: this.staffResult(staff), generatedPin: pin, mockDelivery: delivery }; }
  async updateStaff(actor: AdminTokenPayload, staffId: string, data: UpdateStaffDto) { await this.access.assert(actor, 'staff.update'); const existing = await this.prisma.staffMember.findFirst({ where: { id: staffId, restaurantId: actor.restaurantId } }); if (!existing) throw new NotFoundException('Staff member not found'); const email = data.email === null ? null : data.email?.toLowerCase() ?? existing.email; const phone = data.phone === null ? null : data.phone?.trim() ?? existing.phone; if (!email && !phone) throw new ConflictException('Email or phone is required'); const roles = data.roleIds ? await this.roleIds(actor.restaurantId, data.roleIds) : undefined; const permissions = data.permissionCodes ? await this.permissionIds(data.permissionCodes) : undefined; const staff = await this.prisma.$transaction(async (tx) => { if (roles) await tx.memberRole.deleteMany({ where: { memberId: staffId } }); if (permissions) await tx.memberPermission.deleteMany({ where: { memberId: staffId } }); return tx.staffMember.update({ where: { id: staffId }, data: { firstName: data.firstName?.trim(), lastName: data.lastName?.trim(), email, phone, isActive: data.isActive, roles: roles ? { create: roles.map((roleId) => ({ roleId })) } : undefined, permissions: permissions ? { create: permissions.map((permission) => ({ permissionId: permission.id, isGranted: true })) } : undefined }, include: { roles: { include: { role: true } }, permissions: { include: { permission: true } } } }); }); await this.audit(actor, 'STAFF_UPDATED', 'StaffMember', staffId); return this.staffResult(staff); }
  async deleteStaff(actor: AdminTokenPayload, staffId: string) { await this.access.assert(actor, 'staff.delete'); const staff = await this.prisma.staffMember.updateMany({ where: { id: staffId, restaurantId: actor.restaurantId }, data: { isActive: false } }); if (!staff.count) throw new NotFoundException('Staff member not found'); await this.audit(actor, 'STAFF_SOFT_DELETED', 'StaffMember', staffId); return { id: staffId, isActive: false }; }
  async regeneratePin(actor: AdminTokenPayload, staffId: string, action: 'staff.pin.reset' | 'staff.pin.resend') { await this.access.assert(actor, action); const staff = await this.prisma.staffMember.findFirst({ where: { id: staffId, restaurantId: actor.restaurantId, isActive: true } }); if (!staff) throw new NotFoundException('Active staff member not found'); const pin = String(randomInt(0, 10000)).padStart(4, '0'); await this.prisma.staffMember.update({ where: { id: staff.id }, data: { pinHash: await argon2.hash(pin, { type: argon2.argon2id }) } }); const delivery = this.deliveryTarget(staff); await this.audit(actor, action === 'staff.pin.reset' ? 'PIN_RESET' : 'PIN_RESENT', 'StaffMember', staff.id); await this.audit(actor, 'PIN_DELIVERY_MOCKED', 'StaffMember', staff.id, delivery); return { staffId: staff.id, generatedPin: pin, mockDelivery: delivery }; }

  async listPermissions(actor: AdminTokenPayload) { await this.access.assert(actor, 'roles.view'); return this.prisma.permission.findMany({ select: { code: true, description: true }, orderBy: { code: 'asc' } }); }
  async listRoles(actor: AdminTokenPayload) { await this.access.assert(actor, 'roles.view'); return this.prisma.role.findMany({ where: { restaurantId: actor.restaurantId }, include: { permissions: { include: { permission: true } } }, orderBy: [{ isOwnerRole: 'desc' }, { name: 'asc' }] }); }
  async createRole(actor: AdminTokenPayload, data: SaveRoleDto) { await this.access.assert(actor, 'roles.manage'); const permissions = await this.permissionIds(data.permissionCodes); const role = await this.prisma.role.create({ data: { restaurantId: actor.restaurantId, name: data.name.trim(), description: data.description?.trim(), permissions: { create: permissions.map((permission) => ({ permissionId: permission.id })) } }, include: { permissions: { include: { permission: true } } } }); await this.audit(actor, 'ROLE_CREATED', 'Role', role.id); return role; }
  async updateRole(actor: AdminTokenPayload, roleId: string, data: SaveRoleDto) { await this.access.assert(actor, 'roles.manage'); const role = await this.prisma.role.findFirst({ where: { id: roleId, restaurantId: actor.restaurantId } }); if (!role) throw new NotFoundException('Role not found'); if (role.isOwnerRole) throw new ForbiddenException('The Owner role is protected'); const permissions = await this.permissionIds(data.permissionCodes); const updated = await this.prisma.$transaction(async (tx) => { await tx.rolePermission.deleteMany({ where: { roleId } }); return tx.role.update({ where: { id: roleId }, data: { name: data.name.trim(), description: data.description?.trim(), isActive: true, deletedAt: null, permissions: { create: permissions.map((permission) => ({ permissionId: permission.id })) } }, include: { permissions: { include: { permission: true } } } }); }); await this.audit(actor, 'ROLE_UPDATED', 'Role', roleId); return updated; }
  async deleteRole(actor: AdminTokenPayload, roleId: string) { await this.access.assert(actor, 'roles.manage'); const role = await this.prisma.role.findFirst({ where: { id: roleId, restaurantId: actor.restaurantId } }); if (!role) throw new NotFoundException('Role not found'); if (role.isOwnerRole) throw new ForbiddenException('The Owner role is protected'); await this.prisma.role.update({ where: { id: roleId }, data: { isActive: false, deletedAt: new Date() } }); await this.audit(actor, 'ROLE_SOFT_DELETED', 'Role', roleId); return { id: roleId, isActive: false }; }
}
